import io
import re
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
)

GF_ORANGE = colors.HexColor("#A855F7")
GF_DARK = colors.HexColor("#1E1B3A")
GF_LIGHT = colors.HexColor("#F5F5F5")
GRAY = colors.HexColor("#666666")


def _style(name, parent, **kw):
    s = getSampleStyleSheet()
    base = s[parent]
    return ParagraphStyle(name, parent=base, **kw)


def _para(text: str, style) -> Paragraph:
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    # restore bold markdown **...**
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    return Paragraph(text, style)


def _orange_rule(width="100%", thickness=4):
    return HRFlowable(width=width, thickness=thickness, color=GF_ORANGE, spaceAfter=4)


def _gray_rule(width="100%", thickness=0.5):
    return HRFlowable(width=width, thickness=thickness, color=GRAY, spaceAfter=4)


def build_pdf(hire: dict, documents: dict) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.9 * inch,
        bottomMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()

    # ── shared styles ──────────────────────────────────────────────────────────
    s_title = _style("GFTitle", "Title",
        fontSize=26, textColor=GF_DARK, alignment=TA_CENTER,
        fontName="Helvetica-Bold", spaceAfter=2)

    s_sub = _style("GFSub", "Normal",
        fontSize=15, textColor=GF_ORANGE, alignment=TA_CENTER,
        fontName="Helvetica-Bold", spaceAfter=16)

    s_info = _style("GFInfo", "Normal",
        fontSize=12, textColor=GF_DARK, alignment=TA_CENTER,
        fontName="Helvetica", leading=22)

    s_small = _style("GFSmall", "Normal",
        fontSize=9, textColor=GRAY, alignment=TA_CENTER,
        fontName="Helvetica-Oblique")

    s_sec_hdr = _style("SecHdr", "Heading1",
        fontSize=14, textColor=GF_ORANGE,
        fontName="Helvetica-Bold", spaceBefore=4, spaceAfter=6)

    s_body = _style("Body", "Normal",
        fontSize=10, leading=15, spaceAfter=4, fontName="Helvetica")

    s_bold_line = _style("BoldLine", "Normal",
        fontSize=10, fontName="Helvetica-Bold",
        textColor=GF_DARK, spaceBefore=8, spaceAfter=3)

    s_mono = _style("Mono", "Normal",
        fontSize=9, fontName="Courier",
        leading=13, spaceAfter=2, textColor=GF_DARK)

    s_subhdr = _style("SubHdr", "Normal",
        fontSize=11, fontName="Helvetica-Bold",
        textColor=GF_DARK, spaceBefore=10, spaceAfter=4)

    # ── COVER PAGE ─────────────────────────────────────────────────────────────
    story = []

    story.append(_orange_rule(thickness=8))
    story.append(Spacer(1, 0.2 * inch))

    story.append(Paragraph("ATLAS ONBOARD", s_title))
    story.append(Paragraph("New Hire Onboarding Packet", s_sub))

    story.append(_orange_rule(thickness=2))
    story.append(Spacer(1, 0.25 * inch))

    for label, value in [
        ("Prepared for", hire["name"]),
        ("Role", f"{hire['job_title']} — {hire['department']}"),
        ("Site", hire["site"]),
        ("Start Date", hire["start_date"]),
        ("Manager", hire["manager"]),
        ("Employment Type", hire["employment_type"]),
        ("Generated", datetime.now().strftime("%B %d, %Y at %I:%M %p")),
    ]:
        story.append(Paragraph(f"<b>{label}:</b>  {value}", s_info))

    story.append(Spacer(1, 0.25 * inch))
    story.append(_orange_rule(thickness=2))
    story.append(Spacer(1, 0.15 * inch))
    story.append(Paragraph("CONFIDENTIAL — FOR INTERNAL HR USE ONLY", s_small))
    story.append(Paragraph(
        "Generated by Atlas Onboard — AI Onboarding Automation", s_small))

    story.append(PageBreak())

    # ── DOCUMENT SECTIONS ──────────────────────────────────────────────────────
    sections = [
        ("welcome_email",       "Document 1 — Personalized Welcome Email"),
        ("onboarding_plan",     "Document 2 — 30-60-90 Day Onboarding Plan"),
        ("compliance_checklist","Document 3 — Compliance & Access Checklist"),
        ("first_week_schedule", "Document 4 — First Week Schedule"),
        ("manager_briefing",    "Document 5 — Manager Briefing Note"),
    ]

    for key, heading in sections:
        content = documents.get(key, "Document not available.")

        story.append(_orange_rule(thickness=5))
        story.append(Spacer(1, 4))
        story.append(Paragraph(heading, s_sec_hdr))
        story.append(_gray_rule())
        story.append(Spacer(1, 6))

        for raw_line in content.split("\n"):
            line = raw_line.rstrip()

            if not line:
                story.append(Spacer(1, 4))
                continue

            # Section dividers like ━━━━━
            if set(line.strip()).issubset({"━", "─", "=", "-"}) and len(line.strip()) > 5:
                story.append(_gray_rule(thickness=0.8))
                continue

            # Bold-only line (markdown **text** or **text**)
            if re.match(r"^\*\*[^*]+\*\*$", line.strip()):
                text = line.strip().strip("*")
                story.append(Paragraph(f"<b>{text}</b>", s_bold_line))
                continue

            # Heading with # or ##
            if line.lstrip().startswith("#"):
                text = re.sub(r"^#+\s*", "", line).strip()
                story.append(Paragraph(f"<b>{text}</b>", s_subhdr))
                continue

            # Checklist items
            if re.match(r"^-\s+\[.?\]", line):
                checked = "[x]" in line or "[X]" in line
                text = re.sub(r"^-\s+\[.?\]\s*", "", line)
                checkbox = "☑" if checked else "☐"
                story.append(Paragraph(f"{checkbox}  {text}", s_body))
                continue

            # Bullet points
            if re.match(r"^[-•]\s+", line):
                text = re.sub(r"^[-•]\s+", "", line)
                # re-bold any **...**
                text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
                text = text.replace("&", "&amp;")
                story.append(Paragraph(f"•  {text}", s_body))
                continue

            # Numbered list
            if re.match(r"^\d+\.\s+", line):
                text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", line)
                text = text.replace("&", "&amp;")
                story.append(Paragraph(text, s_body))
                continue

            # ALL-CAPS lines (headers in the manager briefing)
            if line.strip() == line.strip().upper() and len(line.strip()) > 8 and re.search(r"[A-Z]", line):
                story.append(Paragraph(f"<b>{line.strip()}</b>", s_bold_line))
                continue

            # Default body paragraph
            safe = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", line)
            safe = safe.replace("&", "&amp;")
            story.append(Paragraph(safe, s_body))

        story.append(PageBreak())

    # ── BACK COVER ─────────────────────────────────────────────────────────────
    story.append(_orange_rule(thickness=5))
    story.append(Spacer(1, 0.15 * inch))
    story.append(Paragraph("Atlas Onboard — AI Onboarding Document Automation", s_small))
    story.append(Paragraph(
        "This document was AI-generated and should be reviewed by HR before distribution.",
        s_small))
    story.append(Paragraph(
        f"(c) {datetime.now().year} Atlas Onboard — portfolio demo. "
        f'"Meridian Semiconductor" is a fictional company used for demonstration only.',
        s_small))

    doc.build(story)
    return buf.getvalue()
