[server]
headless = true

[theme]
primaryColor = "#C6F135"
backgroundColor = "#14171A"
secondaryBackgroundColor = "#1E2226"
textColor = "#F2F4F1"
font = "sans serif"

[browser]
gatherUsageStats = false
